#########################################
# AdGuard
#########################################

sync_adguard() {
    local DEST="$REPO_DIR/configs/adguard"

    echo "Syncing AdGuard Home config..."

    if [[ "$DRY_RUN" == "true" ]]; then
        echo "[DRY RUN] Would copy AdGuard configuration"
        record_status "adguard" "DRY"
        return
    fi

    mkdir -p "$DEST"

    # Copy main configuration
    pct exec 110 -- \
        cat /opt/AdGuardHome/AdGuardHome.yaml \
        > "$DEST/AdGuardHome.yaml"

    # Sanitize credentials
    sed -Ei \
        -e 's/^([[:space:]]*password:).*/\1 CHANGE_ME/' \
        "$DEST/AdGuardHome.yaml"

    # Copy systemd service definition
    pct exec 110 -- \
        cat /etc/systemd/system/AdGuardHome.service \
        > "$DEST/AdGuardHome.service"

    # Capture version information
    pct exec 110 -- \
        /opt/AdGuardHome/AdGuardHome --version \
        > "$DEST/version.txt" || true
    
    #########################################
    # Generate README
    #########################################

    cat > "$DEST/README.md" <<EOF
# AdGuard Home Configuration

## Overview

AdGuard Home provides network-wide DNS filtering and blocking for
the homelab.

## Deployment

AdGuard Home runs as a native systemd service in Proxmox LXC CT110.

Binary:

\`\`\`
/opt/AdGuardHome/AdGuardHome
\`\`\`

Configuration:

\`\`\`
/opt/AdGuardHome/AdGuardHome.yaml
\`\`\`

Systemd service:

\`\`\`
AdGuardHome.service
\`\`\`

## Tracked Configuration

The following configuration is exported to Git:

- \`AdGuardHome.yaml\`
- \`AdGuardHome.service\`

The exported configuration is intended to provide a human-readable
and reproducible representation of the service configuration.

## Runtime Data

Runtime data is intentionally excluded from Git.

This includes:

- Query history
- Statistics
- Runtime state
- Other instance-specific data

## Redundancy

This instance is part of a redundant DNS setup with a Raspberry Pi
running AdGuard Home.

The Raspberry Pi configuration is backed up separately.

## Backup

The AdGuard Home LXC is protected by the normal Proxmox backup
process.

The exported configuration is also tracked in the homelab Git
repository.

## Configuration Management

This documentation is generated by:

\`\`\`
scripts/export-configs.sh
\`\`\`

The README is regenerated during each configuration export.

EOF

    record_status "adguard" "OK"
}
