#########################################
# Caddy
#########################################

sync_caddy() {
    local DEST="$REPO_DIR/configs/caddy"

    echo "Syncing Caddy config..."

    if [[ "$DRY_RUN" == "true" ]]; then
        echo "[DRY RUN] Would copy Caddy configuration"
        record_status "caddy" "DRY"
        return
    fi

    mkdir -p "$DEST"

    pct exec 120 -- \
        tar \
        -C /etc/caddy \
        -cf - \
        sites snippets Caddyfile \
        | tar -C "$DEST" -xf -

    #########################################
    # Generate README
    #########################################

    cat > "$DEST/README.md" <<EOF
# Caddy Configuration

## Overview

Caddy provides HTTPS termination and reverse proxying for services
exposed through the homelab.

## Deployment

Caddy runs as a native service in the Proxmox reverse proxy LXC.

The primary configuration is:

\`\`\`
/etc/caddy/Caddyfile
\`\`\`

## Tracked Configuration

The following configuration is exported to Git:

- \`Caddyfile\`
- \`sites/\`
- \`snippets/\`

The configuration is organized so that individual services can be
managed independently while reusable proxy configuration is kept in
shared snippets.

## Network

Caddy acts as the external HTTPS entry point for services published
through the homelab reverse proxy.

Service-specific virtual hosts are defined under:

\`\`\`
sites/
\`\`\`

Reusable configuration blocks are defined under:

\`\`\`
snippets/
\`\`\`

## Secrets

Credentials and other sensitive values are intentionally excluded
from Git.

This includes:

- Cloudflare API tokens
- Other API credentials
- Private or environment-specific secrets

Secrets are provided separately to the live Caddy installation.

## Runtime Data

Caddy runtime state and other instance-specific data are intentionally
excluded from Git where applicable.

## Backup

The Caddy LXC is protected by the normal Proxmox backup process.

The exported configuration is also tracked in the homelab Git
repository.

## Configuration Management

This documentation is generated by:

\`\`\`
scripts/export-configs.sh
\`\`\`

The README is regenerated during each configuration export.

EOF

    record_status "caddy" "OK"
}
