#########################################
# Docker
#########################################

DOCKER_ENABLED=true
DOCKER_DISABLED_REASON=""

sync_docker() {
    local DEST="$REPO_DIR/configs/docker"

    echo "Syncing Docker config..."

    #########################################
    # Disabled
    #########################################

    if [[ "$DOCKER_ENABLED" != "true" ]]; then
        echo "Docker export disabled; skipping."

        mkdir -p "$DEST"

        cat > "$DEST/README.md" <<EOF
# Docker Configuration

## Status

Docker configuration export is currently **disabled**.

**Reason:** $DOCKER_DISABLED_REASON

No live Docker configuration is synchronized to this directory.

To re-enable the export, set:

\`\`\`
DOCKER_ENABLED=true
\`\`\`

in:

\`\`\`
scripts/services/docker.sh
\`\`\`

EOF

        record_status "docker" "DISABLED"
        return 0
    fi

    #########################################
    # Dry Run
    #########################################

    if [[ "$DRY_RUN" == "true" ]]; then
        echo "[DRY RUN] Would copy Docker configuration"
        record_status "docker" "DRY"
        return 0
    fi

    #########################################
    # Container Check
    #########################################

    if ! is_lxc_running 100; then
        echo "ERROR: Docker container CT100 is not running."
        record_status "docker" "FAILED"
        return 1
    fi

    #########################################
    # Prepare Destination
    #########################################

    if ! mkdir -p "$DEST"; then
        echo "ERROR: Failed to create Docker export directory."
        record_status "docker" "FAILED"
        return 1
    fi

    #########################################
    # Capture Version Information
    #########################################

    if ! pct exec 100 -- bash -c '
        docker --version
        docker compose version
        containerd --version
    ' > "$DEST/versions.txt"; then

        echo "ERROR: Failed to capture Docker version information."
        record_status "docker" "FAILED"
        return 1
    fi

    #########################################
    # Capture Installed Packages
    #########################################

    if ! pct exec 100 -- bash -c '
        dpkg --get-selections | grep -E "docker|containerd|runc"
    ' > "$DEST/packages.txt"; then

        echo "ERROR: Failed to capture Docker package information."
        record_status "docker" "FAILED"
        return 1
    fi

    #########################################
    # Generate README
    #########################################

    cat > "$DEST/README.md" <<EOF
# Docker Host Configuration

## Overview

Docker provides the container runtime for application services hosted
on the homelab Docker LXC.

## Deployment

Docker runs inside Proxmox LXC CT100.

Host:

\`\`\`
docker
\`\`\`

The Docker engine uses its default configuration. No custom
\`/etc/docker/daemon.json\` configuration is currently present.

## Tracked Configuration

This directory contains configuration specific to the Docker engine
and host environment.

Application-specific Docker stacks are maintained separately, including:

- \`configs/homepage\`
- \`configs/paperless\`
- \`configs/portainer\`
- \`configs/samba\`

Additional application stacks are maintained in their respective
configuration directories.

## Runtime Data

Docker runtime data is stored outside Git:

\`\`\`
/var/lib/docker
\`\`\`

This includes:

- Container layers
- Images
- Volumes
- Container runtime state
- Docker-managed metadata

Runtime data is intentionally excluded from Git and is protected by
the homelab backup strategy.

## Application Stacks

Docker Compose application stacks are stored on the Docker LXC under:

\`\`\`
/opt/stacks
\`\`\`

Each application manages its own configuration and documentation
within the corresponding service directory.

## Storage

Docker uses the following primary locations:

Docker data:

\`\`\`
/var/lib/docker
\`\`\`

Application stacks:

\`\`\`
/opt/stacks
\`\`\`

## Backup

The Docker LXC is protected by the normal Proxmox backup process.

Application configuration exported to the homelab Git repository is
backed up separately through the configuration export process.

## Configuration Management

This documentation is generated by:

\`\`\`
scripts/export-configs.sh
\`\`\`

The README is regenerated during each configuration export.

EOF

    #########################################
    # Success
    #########################################

    record_status "docker" "OK"
    echo "Docker configuration exported successfully."

    return 0
}
