#########################################
# Home Assistant
#########################################

sync_homeassistant() {
    local DEST="$REPO_DIR/configs/homeassistant"

    echo "Syncing Home Assistant config..."

    if [[ "$DRY_RUN" == "true" ]]; then
        echo "[DRY RUN] Would copy Home Assistant configuration"
        record_status "homeassistant" "DRY"
        return
    fi

    mkdir -p "$DEST"

    # Copy Home Assistant configuration files
    pct exec 140 -- tar \
        --exclude='./.storage' \
        --exclude='./.cache' \
        --exclude='./deps' \
        --exclude='./backups' \
        --exclude='./*.db' \
        --exclude='./*.db-*' \
        --exclude='./*.log' \
        --exclude='./secrets.yaml' \
        -C /opt/homeassistant/config \
        -cf - \
        configuration.yaml \
        automations.yaml \
        scripts.yaml \
        scenes.yaml \
        blueprints \
        custom_components \
        www \
    | tar -C "$DEST" -xf -

    #########################################
    # Create secrets template
    #########################################
    cat > "$DEST/secrets.yaml.example" <<EOF
# Home Assistant secrets template
#
# Copy this file to:
# /opt/homeassistant/config/secrets.yaml
#
# Then replace values with real secrets.

# Example:
# mqtt_username: CHANGE_ME
# mqtt_password: CHANGE_ME
# api_key: CHANGE_ME
EOF

    #########################################
    # Generate README
    #########################################

    cat > "$DEST/README.md" <<EOF
# Home Assistant Configuration

## Overview

Home Assistant provides home automation and device integration for
the homelab.

## Deployment

Home Assistant runs in Proxmox LXC CT140.

The live configuration is stored at:

\`\`\`
/opt/homeassistant/config
\`\`\`

## Tracked Configuration

The following configuration is exported to Git:

- \`configuration.yaml\`
- \`automations.yaml\`
- \`scripts.yaml\`
- \`scenes.yaml\`
- \`blueprints/\`
- \`custom_components/\`
- \`www/\`
- \`secrets.yaml.example\`

The exported configuration provides a sanitized representation of the
Home Assistant setup without including instance-specific runtime data
or credentials.

## Runtime Data

The following Home Assistant data is intentionally excluded from Git:

- \`.storage/\`
- \`.cache/\`
- \`deps/\`
- \`backups/\`
- Database files
- Database journal files
- Log files

Runtime data is protected separately by the homelab backup strategy.

## Secrets

\`secrets.yaml\` is intentionally excluded from Git.

A sanitized template is provided as:

\`\`\`
secrets.yaml.example
\`\`\`

Copy the template to the Home Assistant configuration directory and
replace the example values with the required secrets before deployment.

Secrets should never be committed to Git.

## Backup

The Home Assistant LXC is protected by the normal Proxmox backup
process.

The sanitized configuration is also tracked in the homelab Git
repository.

## Configuration Management

This documentation is generated by:

\`\`\`
scripts/export-configs.sh
\`\`\`

The README is regenerated during each configuration export.

EOF

    record_status "homeassistant" "OK"
}
