#########################################
# Homepage
#########################################

HOMEPAGE_ENABLED=true
HOMEPAGE_DISABLED_REASON=""

sync_homepage() {
    local DEST="$REPO_DIR/configs/homepage"

    echo "Syncing Homepage config..."

    #########################################
    # Disabled
    #########################################

    if [[ "$HOMEPAGE_ENABLED" != "true" ]]; then
        echo "Homepage export disabled; skipping."

        mkdir -p "$DEST"

        cat > "$DEST/README.md" <<EOF
# Homepage Configuration

## Status

Homepage configuration export is currently **disabled**.

**Reason:** $HOMEPAGE_DISABLED_REASON

No live Homepage configuration is synchronized to this directory.

To re-enable the export, set:

\`\`\`
HOMEPAGE_ENABLED=true
\`\`\`

in:

\`\`\`
scripts/services/homepage.sh
\`\`\`

EOF

        record_status "homepage" "DISABLED"
        return 0
    fi

    #########################################
    # Dry Run
    #########################################

    if [[ "$DRY_RUN" == "true" ]]; then
        echo "[DRY RUN] Would copy Homepage configuration"
        record_status "homepage" "DRY"
        return 0
    fi

    #########################################
    # Container Check
    #########################################

    if ! is_lxc_running 100; then
        echo "ERROR: Homepage container CT100 is not running."
        record_status "homepage" "FAILED"
        return 1
    fi

    #########################################
    # Prepare Destination
    #########################################

    if ! mkdir -p "$DEST"; then
        echo "ERROR: Failed to create Homepage export directory."
        record_status "homepage" "FAILED"
        return 1
    fi

    #########################################
    # Copy Docker Compose Configuration
    #########################################

    if ! copy_pct_file \
        100 \
        /opt/stacks/homepage/docker-compose.yml \
        "$DEST/docker-compose.yml"; then

        echo "ERROR: Failed to export Homepage docker-compose.yml."
        record_status "homepage" "FAILED"
        return 1
    fi

    #########################################
    # Copy Homepage Configuration
    #########################################

    if ! copy_pct_dir \
        100 \
        /opt/stacks/homepage/config \
        "$DEST"; then

        echo "ERROR: Failed to export Homepage configuration."
        record_status "homepage" "FAILED"
        return 1
    fi

    #########################################
    # Remove Runtime Logs
    #########################################

    rm -rf "$DEST/config/logs"

    #########################################
    # Sanitize Proxmox Credentials
    #########################################

    if [[ -f "$DEST/config/proxmox.yaml" ]]; then
        if ! sed -Ei \
            -e 's/^([[:space:]]*token:).*/\1 <REDACTED>/' \
            -e 's/^([[:space:]]*secret:).*/\1 <REDACTED>/' \
            "$DEST/config/proxmox.yaml"; then

            echo "ERROR: Failed to sanitize Homepage Proxmox credentials."
            record_status "homepage" "FAILED"
            return 1
        fi
    fi

    #########################################
    # Generate README
    #########################################

    cat > "$DEST/README.md" <<EOF
# Homepage Configuration

## Overview

Homepage is the homelab dashboard used to provide a centralized view
of services, bookmarks, widgets, and infrastructure integrations.

## Deployment

Homepage runs as a Docker Compose application on Proxmox LXC CT100.

Live stack directory:

\`\`\`
/opt/stacks/homepage
\`\`\`

The stack is managed with Docker Compose.

## Tracked Configuration

The following configuration is exported to Git:

- \`docker-compose.yml\`
- \`config/\`

The configuration includes:

- Service definitions
- Dashboard settings
- Widgets
- Bookmarks
- Docker integration
- Proxmox integration

Runtime logs are excluded from the exported configuration.

## Secrets

Credentials used by service integrations are intentionally excluded
from Git.

During export, sensitive Proxmox integration values such as API tokens
and secrets are replaced with:

\`\`\`
<REDACTED>
\`\`\`

Secrets should never be committed to Git.

## Runtime Data

Homepage runtime logs are intentionally excluded from Git.

The exported configuration represents the dashboard configuration
required to recreate the service rather than its runtime state.

## Backup

The Docker LXC containing Homepage is protected by the normal Proxmox
backup process.

The sanitized Homepage configuration is also tracked in the homelab
Git repository.

## Configuration Management

This documentation is generated by:

\`\`\`
scripts/export-configs.sh
\`\`\`

The README is regenerated during each configuration export.

EOF

    #########################################
    # Success
    #########################################

    record_status "homepage" "OK"
    echo "Homepage configuration exported successfully."

    return 0
}
