#########################################
# Home Assistant
#########################################

HOMEASSISTANT_ENABLED=true
HOMEASSISTANT_DISABLED_REASON=""

sync_homeassistant() {
    local DEST="$REPO_DIR/configs/homeassistant"

    echo "Syncing Home Assistant config..."

    #########################################
    # Disabled
    #########################################

    if [[ "$HOMEASSISTANT_ENABLED" != "true" ]]; then
        echo "Home Assistant export disabled; skipping."

        mkdir -p "$DEST"

        cat > "$DEST/README.md" <<EOF
# Home Assistant Configuration

## Status

Home Assistant configuration export is currently **disabled**.

**Reason:** $HOMEASSISTANT_DISABLED_REASON

No live Home Assistant configuration is synchronized to this directory.

To re-enable the export, set:

\`\`\`
HOMEASSISTANT_ENABLED=true
\`\`\`

in:

\`\`\`
scripts/services/homeassistant.sh
\`\`\`

EOF

        record_status "homeassistant" "DISABLED"
        return 0
    fi

    #########################################
    # Dry Run
    #########################################

    if [[ "$DRY_RUN" == "true" ]]; then
        echo "[DRY RUN] Would copy Home Assistant configuration"
        record_status "homeassistant" "DRY"
        return 0
    fi

    #########################################
    # Container Check
    #########################################

    if ! is_lxc_running 140; then
        echo "ERROR: Home Assistant container CT140 is not running."
        record_status "homeassistant" "FAILED"
        return 1
    fi

    #########################################
    # Prepare Destination
    #########################################

    if ! mkdir -p "$DEST"; then
        echo "ERROR: Failed to create Home Assistant export directory."
        record_status "homeassistant" "FAILED"
        return 1
    fi

    #########################################
    # Copy Configuration
    #########################################

    if ! pct exec 140 -- tar \
        --exclude='./.storage' \
        --exclude='./.cache' \
        --exclude='./deps' \
        --exclude='./backups' \
        --exclude='./*.db' \
        --exclude='./*.db-*' \
        --exclude='./*.log' \
        --exclude='./secrets.yaml' \
        -C /opt/homeassistant/config \
        -cf - \
        configuration.yaml \
        automations.yaml \
        scripts.yaml \
        scenes.yaml \
        blueprints \
        custom_components \
        www \
    | tar -C "$DEST" -xf -; then

        echo "ERROR: Failed to export Home Assistant configuration."
        record_status "homeassistant" "FAILED"
        return 1
    fi

    #########################################
    # Generate README
    #########################################

    cat > "$DEST/README.md" <<EOF
# Home Assistant Configuration

## Overview

Home Assistant provides home automation and device integration for
the homelab.

## Deployment

Home Assistant runs in Proxmox LXC CT140.

The live configuration is stored at:

\`\`\`
/opt/homeassistant/config
\`\`\`

## Tracked Configuration

The following configuration is exported to Git:

- \`configuration.yaml\`
- \`automations.yaml\`
- \`scripts.yaml\`
- \`scenes.yaml\`
- \`blueprints/\`
- \`custom_components/\`
- \`www/\`

The exported configuration provides a sanitized representation of the
Home Assistant setup without including instance-specific runtime data
or credentials.

## Runtime Data

The following Home Assistant data is intentionally excluded from Git:

- \`.storage/\`
- \`.cache/\`
- \`deps/\`
- \`backups/\`
- Database files
- Database journal files
- Log files

Runtime data is protected separately by the homelab backup strategy.

## Secrets

Home Assistant does not currently use a \`secrets.yaml\` file in this
deployment.

If secrets are introduced in the future, they should be stored outside
Git and represented by a sanitized template when appropriate.

## Backup

The Home Assistant LXC is protected by the normal Proxmox backup
process.

The sanitized configuration is also tracked in the homelab Git
repository.

## Configuration Management

This documentation is generated by:

\`\`\`
scripts/export-configs.sh
\`\`\`

The README is regenerated during each configuration export.

EOF

    #########################################
    # Success
    #########################################

    record_status "homeassistant" "OK"
    echo "Home Assistant configuration exported successfully."

    return 0
}
