#########################################
# Jellyfin
#########################################

sync_jellyfin() {
    local DEST="$REPO_DIR/configs/jellyfin"

    echo "Syncing Jellyfin config..."

    if [[ "$DRY_RUN" == "true" ]]; then
        echo "[DRY RUN] Would copy Jellyfin configuration"
        record_status "jellyfin" "DRY"
        return
    fi

    mkdir -p "$DEST"

    # Remove previous exported config directory
    rm -rf "$DEST/config"

    mkdir -p "$DEST/config"

    # Jellyfin environment configuration
    pct exec 101 -- cat /etc/default/jellyfin \
        > "$DEST/default-jellyfin"

    # Systemd override configuration
    if pct exec 101 -- test -f /etc/systemd/system/jellyfin.service.d/jellyfin.service.conf; then
        pct exec 101 -- cat /etc/systemd/system/jellyfin.service.d/jellyfin.service.conf \
            > "$DEST/service-override.conf"
    fi

    # Export Jellyfin configuration files
    pct exec 101 -- tar \
        --exclude='./data' \
        --exclude='./cache' \
        --exclude='./logs' \
        --exclude='./transcodes' \
        -C /etc/jellyfin \
        -cf - \
        . \
    | tar -C "$DEST/config" -xf -

    # Remove runtime files if present
    rm -rf \
        "$DEST/config/data" \
        "$DEST/config/cache" \
        "$DEST/config/logs"

    # Capture media library mount structure
    pct exec 101 -- bash -c \
        'find /media -maxdepth 2 -type d | sort' \
        > "$DEST/libraries.txt"

    #########################################
    # Generate README
    #########################################

    cat > "$DEST/README.md" <<EOF
# Jellyfin Configuration

## Overview

Jellyfin provides self-hosted media streaming for the homelab.

## Deployment

Jellyfin is installed directly on Proxmox LXC CT101 as a native
systemd service.

System configuration:

\`\`\`
/etc/jellyfin
\`\`\`

Runtime data:

\`\`\`
/var/lib/jellyfin
\`\`\`

## Tracked Configuration

The following configuration is exported to Git:

- \`default-jellyfin\`
- \`service-override.conf\`
- \`config/\`
- \`libraries.txt\`

The exported configuration provides a sanitized representation of the
Jellyfin installation without including runtime application data.

## Runtime Data

Jellyfin runtime data is intentionally excluded from Git.

This includes:

- Database
- Metadata
- Cache
- Transcoding files
- Logs

Runtime data is protected separately by the homelab backup strategy.

## Media Libraries

Media files are stored separately from the Jellyfin configuration.

Configured library locations include:

\`\`\`
/media/Movies
/media/TV
/media/Music
\`\`\`

The actual media files are not stored in Git.

The exported \`libraries.txt\` file documents the configured library
structure using a sanitized representation of the media paths.

## Backup

The Jellyfin LXC is protected by the normal Proxmox backup process.

Media storage is protected separately by the homelab storage and backup
strategy.

The exported Jellyfin configuration is also tracked in the homelab
Git repository.

## Configuration Management

This documentation is generated by:

\`\`\`
scripts/export-configs.sh
\`\`\`

The README is regenerated during each configuration export.

EOF

    record_status "jellyfin" "OK"

}
