#########################################
# Paperless
#########################################

PAPERLESS_ENABLED=true
PAPERLESS_DISABLED_REASON=""

sync_paperless() {
    local DEST="$REPO_DIR/configs/paperless"

    echo "Syncing Paperless config..."

    #########################################
    # Disabled
    #########################################

    if [[ "$PAPERLESS_ENABLED" != "true" ]]; then
        echo "Paperless export disabled; skipping."

        mkdir -p "$DEST"

        cat > "$DEST/README.md" <<EOF
# Paperless Configuration

## Status

Paperless configuration export is currently **disabled**.

**Reason:** $PAPERLESS_DISABLED_REASON

No live Paperless configuration is synchronized to this directory.

To re-enable the export, set:

\`\`\`
PAPERLESS_ENABLED=true
\`\`\`

in:

\`\`\`
scripts/services/paperless.sh
\`\`\`

EOF

        record_status "paperless" "DISABLED"
        return 0
    fi

    #########################################
    # Dry Run
    #########################################

    if [[ "$DRY_RUN" == "true" ]]; then
        echo "[DRY RUN] Would copy Paperless configuration"
        record_status "paperless" "DRY"
        return 0
    fi

    #########################################
    # Container Check
    #########################################

    if ! is_lxc_running 100; then
        echo "ERROR: Paperless container CT100 is not running."
        record_status "paperless" "FAILED"
        return 1
    fi

    #########################################
    # Prepare Destination
    #########################################

    if ! mkdir -p "$DEST"; then
        echo "ERROR: Failed to create Paperless export directory."
        record_status "paperless" "FAILED"
        return 1
    fi

    #########################################
    # Copy Docker Compose Configuration
    #########################################

    if ! copy_pct_file \
        100 \
        /opt/stacks/paperless/docker-compose.yml \
        "$DEST/docker-compose.yml"; then

        echo "ERROR: Failed to export Paperless docker-compose.yml."
        record_status "paperless" "FAILED"
        return 1
    fi

    #########################################
    # Create Sanitized Environment Template
    #########################################

    cat > "$DEST/.env.example" <<EOF
# Paperless-ngx environment variables

# Generate a secure key:
# openssl rand -hex 32

PAPERLESS_SECRET_KEY=CHANGE_ME

# PostgreSQL database password

POSTGRES_PASSWORD=CHANGE_ME
EOF

    #########################################
    # Generate README
    #########################################

    cat > "$DEST/README.md" <<EOF
# Paperless-ngx Configuration

## Overview

Paperless-ngx provides document management and archival capabilities
for the homelab.

This directory contains the infrastructure configuration required to
recreate the Paperless-ngx deployment. Application data and documents
are backed up separately and are not stored in Git.

## Deployment

Paperless-ngx runs as a Docker Compose deployment on Proxmox LXC
CT100.

Live stack directory:

\`\`\`
/opt/stacks/paperless
\`\`\`

## Tracked Configuration

The following configuration is exported to Git:

- \`docker-compose.yml\`
- \`.env.example\`

The exported files document the deployment configuration while
omitting sensitive values and application data.

## Storage

Paperless-ngx application data and documents are stored outside the
Git repository.

Application data:

\`\`\`
/storage/paperless/data
\`\`\`

Database:

\`\`\`
/storage/paperless/db
\`\`\`

Document media:

\`\`\`
/documents/paperless/media
\`\`\`

Exported documents:

\`\`\`
/documents/paperless/export
\`\`\`

Document consumption directory:

\`\`\`
/documents/paperless/consume
\`\`\`

These locations contain application state and documents and are backed
up separately by the Paperless backup process.

## Secrets

The live deployment stores environment variables and secrets in:

\`\`\`
/opt/stacks/paperless/.env
\`\`\`

The live \`.env\` file is intentionally excluded from Git.

A sanitized template is provided as:

\`\`\`
.env.example
\`\`\`

Sensitive values must be supplied separately when recreating the
deployment.

Secrets should never be committed to Git.

## Runtime Data

The following types of data are intentionally excluded from Git:

- Paperless application data
- Database contents
- Stored documents
- Exported documents
- Consumed document files
- Other instance-specific runtime state

The Git repository contains deployment configuration, not a backup of
the Paperless-ngx application data or documents.

## Backup

Paperless-ngx application data and documents are protected separately
by the Paperless backup process.

The Docker LXC containing the service is also protected by the normal
Proxmox backup process.

The exported deployment configuration is tracked in the homelab Git
repository.

## Configuration Management

This documentation is generated by:

\`\`\`
scripts/export-configs.sh
\`\`\`

The README is regenerated during each configuration export.

EOF

    #########################################
    # Success
    #########################################

    record_status "paperless" "OK"
    echo "Paperless configuration exported successfully."

    return 0
}
