#########################################
# Plex
#########################################

PLEX_ENABLED=false
PLEX_DISABLED_REASON="Plex is no longer actively used."

sync_plex() {
    local DEST="$REPO_DIR/configs/plex"

    echo "Syncing Plex config..."

    #########################################
    # Disabled
    #########################################

    if [[ "$PLEX_ENABLED" != "true" ]]; then
        echo "Plex export disabled; skipping."

        mkdir -p "$DEST"

        cat > "$DEST/README.md" <<EOF
# Plex Configuration

## Status

Plex configuration export is currently **disabled**.

**Reason:** $PLEX_DISABLED_REASON

No live Plex configuration is synchronized to this directory.

To re-enable the export, set:

\`\`\`
PLEX_ENABLED=true
\`\`\`

in:

\`\`\`
scripts/services/plex.sh
\`\`\`

EOF

        record_status "plex" "DISABLED"
        return 0
    fi

    #########################################
    # Dry Run
    #########################################

    if [[ "$DRY_RUN" == "true" ]]; then
        echo "[DRY RUN] Would copy Plex configuration"
        record_status "plex" "DRY"
        return 0
    fi

    #########################################
    # Container Check
    #########################################

    if ! is_lxc_running 102; then
        echo "ERROR: Plex container CT102 is not running."
        record_status "plex" "FAILED"
        return 1
    fi

    #########################################
    # Prepare Destination
    #########################################

    if ! mkdir -p "$DEST"; then
        echo "ERROR: Failed to create Plex export directory."
        record_status "plex" "FAILED"
        return 1
    fi

    #########################################
    # Capture Service Configuration
    #########################################

    if ! pct exec 102 -- systemctl cat plexmediaserver \
        > "$DEST/service-info.txt"; then

        echo "ERROR: Failed to export Plex service configuration."
        record_status "plex" "FAILED"
        return 1
    fi

    #########################################
    # Capture Media Library Paths
    #########################################

    if ! pct exec 102 -- bash -c \
        'find /media -maxdepth 2 -type d | sort' \
        > "$DEST/libraries.txt"; then

        echo "ERROR: Failed to export Plex library paths."
        record_status "plex" "FAILED"
        return 1
    fi

    #########################################
    # Generate README
    #########################################

    cat > "$DEST/README.md" <<EOF
# Plex Configuration

## Overview

Plex Media Server provides self-hosted media streaming for the
homelab.

## Deployment

Plex Media Server is installed directly on Proxmox LXC CT102 as a
native systemd service.

Systemd service:

\`\`\`
plexmediaserver.service
\`\`\`

The service uses the default configuration provided by the Plex
package.

## Tracked Configuration

The configuration exported to Git represents the service configuration
required to document the Plex installation.

The Plex service definition is managed by the Plex package and should
not be manually modified.

## Runtime Data

Plex application data is intentionally excluded from Git.

Runtime data is stored at:

\`\`\`
/var/lib/plexmediaserver
\`\`\`

This includes:

- Database
- Metadata
- Posters
- Cache
- Transcoding data

Runtime data is protected separately by the homelab backup strategy.

## Media Libraries

Media files are stored separately from the Plex configuration.

Configured library locations include:

\`\`\`
/media/Movies
/media/TV
/media/Music
/media/Photos
\`\`\`

The actual media files are not stored in Git.

## Backup

The Plex LXC is protected by the normal Proxmox backup process.

Media storage is protected separately by the homelab backup process.

The exported Plex configuration is also tracked in the homelab Git
repository.

## Configuration Management

This documentation is generated by:

\`\`\`
scripts/export-configs.sh
\`\`\`

The README is regenerated during each configuration export.

EOF

    #########################################
    # Success
    #########################################

    record_status "plex" "OK"
    echo "Plex configuration exported successfully."

    return 0
}
