#########################################
# Plex
#########################################

sync_plex() {
    local DEST="$REPO_DIR/configs/plex"

    echo "Syncing Plex config..."

    if [[ "$DRY_RUN" == "true" ]]; then
        echo "[DRY RUN] Would copy Plex configuration"
        record_status "plex" "DRY"
        return
    fi

    mkdir -p "$DEST"

    # Capture Plex service configuration summary
    pct exec 102 -- systemctl cat plexmediaserver \
        > "$DEST/service-info.txt"

    # Capture media library paths
    pct exec 102 -- bash -c \
        'find /media -maxdepth 2 -type d | sort' \
        > "$DEST/libraries.txt"

    #########################################
    # Generate README
    #########################################

    cat > "$DEST/README.md" <<EOF
# Plex Configuration

## Overview

Plex Media Server provides self-hosted media streaming for the
homelab.

## Deployment

Plex Media Server is installed directly on Proxmox LXC CT102 as a
native systemd service.

Systemd service:

\`\`\`
plexmediaserver.service
\`\`\`

The service uses the default configuration provided by the Plex
package.

## Tracked Configuration

The configuration exported to Git represents the service configuration
required to document the Plex installation.

The Plex service definition is managed by the Plex package and should
not be manually modified.

## Runtime Data

Plex application data is intentionally excluded from Git.

Runtime data is stored at:

\`\`\`
/var/lib/plexmediaserver
\`\`\`

This includes:

- Database
- Metadata
- Posters
- Cache
- Transcoding data

Runtime data is protected separately by the homelab backup strategy.

## Media Libraries

Media files are stored separately from the Plex configuration.

Configured library locations include:

\`\`\`
/media/Movies
/media/TV
/media/Music
/media/Photos
\`\`\`

The actual media files are not stored in Git.

## Backup

The Plex LXC is protected by the normal Proxmox backup process.

Media storage is protected separately by the homelab storage and backup
strategy.

The exported Plex configuration is also tracked in the homelab Git
repository.

## Configuration Management

This documentation is generated by:

\`\`\`
scripts/export-configs.sh
\`\`\`

The README is regenerated during each configuration export.

EOF

    record_status "plex" "OK"
}
