#########################################
# Portainer
#########################################

PORTAINER_ENABLED=true
PORTAINER_DISABLED_REASON=""

sync_portainer() {
    local DEST="$REPO_DIR/configs/portainer"

    echo "Syncing Portainer config..."

    #########################################
    # Disabled
    #########################################

    if [[ "$PORTAINER_ENABLED" != "true" ]]; then
        echo "Portainer export disabled; skipping."

        mkdir -p "$DEST"

        cat > "$DEST/README.md" <<EOF
# Portainer Configuration

## Status

Portainer configuration export is currently **disabled**.

**Reason:** $PORTAINER_DISABLED_REASON

No live Portainer configuration is synchronized to this directory.

To re-enable the export, set:

\`\`\`
PORTAINER_ENABLED=true
\`\`\`

in:

\`\`\`
scripts/services/portainer.sh
\`\`\`

EOF

        record_status "portainer" "DISABLED"
        return 0
    fi

    #########################################
    # Dry Run
    #########################################

    if [[ "$DRY_RUN" == "true" ]]; then
        echo "[DRY RUN] Would copy Portainer configuration"
        record_status "portainer" "DRY"
        return 0
    fi

    #########################################
    # Container Check
    #########################################

    if ! is_lxc_running 100; then
        echo "ERROR: Portainer container CT100 is not running."
        record_status "portainer" "FAILED"
        return 1
    fi

    #########################################
    # Prepare Destination
    #########################################

    if ! mkdir -p "$DEST"; then
        echo "ERROR: Failed to create Portainer export directory."
        record_status "portainer" "FAILED"
        return 1
    fi

    #########################################
    # Copy Docker Compose Configuration
    #########################################

    if ! copy_pct_file \
        100 \
        /opt/stacks/portainer/docker-compose.yml \
        "$DEST/docker-compose.yml"; then

        echo "ERROR: Failed to export Portainer docker-compose.yml."
        record_status "portainer" "FAILED"
        return 1
    fi

    #########################################
    # Generate README
    #########################################

    cat > "$DEST/README.md" <<EOF
# Portainer Configuration

## Overview

Portainer provides a web-based management interface for the Docker
environment hosted on the homelab Docker LXC.

## Deployment

Portainer runs as a Docker Compose deployment on Proxmox LXC CT100.

Live stack directory:

\`\`\`
/opt/stacks/portainer
\`\`\`

## Tracked Configuration

The Docker Compose configuration required to deploy Portainer is
exported to Git.

The repository contains deployment configuration rather than
Portainer's application state.

## Runtime Data

Portainer stores its persistent application data in the Docker volume:

\`\`\`
portainer_data
\`\`\`

The volume is intentionally excluded from Git.

This includes Portainer application state and other runtime data
managed by Portainer.

## Backup

The Portainer Docker volume is backed up separately as part of the
homelab backup strategy.

The Docker LXC containing Portainer is also protected by the normal
Proxmox backup process.

The exported deployment configuration is tracked in the homelab Git
repository.

## Configuration Management

This documentation is generated by:

\`\`\`
scripts/export-configs.sh
\`\`\`

The README is regenerated during each configuration export.

EOF

    #########################################
    # Success
    #########################################

    record_status "portainer" "OK"
    echo "Portainer configuration exported successfully."

    return 0
}
