#########################################
# Samba
#########################################

sync_samba() {
    local DEST="$REPO_DIR/configs/samba"

    echo "Syncing Samba config..."

    if [[ "$DRY_RUN" == "true" ]]; then
        echo "[DRY RUN] Would copy Samba configuration"
        record_status "samba" "DRY"
        return
    fi

    mkdir -p "$DEST"

    # Copy Docker Compose file
    copy_pct_file \
        100 \
        /opt/stacks/samba/docker-compose.yml \
        "$DEST/docker-compose.yml"

    # Create sanitized environment template
    cat > "$DEST/.env.example" <<EOF
# Samba credentials

SAMBA_USER=CHANGE_ME
SAMBA_PASSWORD=CHANGE_ME
EOF

    # Remove any local environment file if accidentally copied
    rm -f "$DEST/.env"

    #########################################
    # Generate README
    #########################################

    cat > "$DEST/README.md" <<EOF
# Samba Configuration

## Overview

Samba provides network file sharing for selected homelab storage
locations.

## Deployment

Samba runs as a Docker Compose service on Proxmox LXC CT100.

Live stack directory:

\`\`\`
/opt/stacks/samba
\`\`\`

The service is managed with Docker Compose:

\`\`\`bash
docker compose up -d
\`\`\`

## Tracked Configuration

The Samba deployment configuration is exported to Git.

The exported configuration documents the Docker Compose deployment
without including credentials or the underlying shared data.

## Storage

The Samba container provides access to the following host storage
locations:

\`\`\`
/storage/media
/storage/downloads
/storage/documents
\`\`\`

These directories contain the underlying shared data and are not
stored in the Git repository.

Samba provides network access to this data but does not serve as the
primary storage or backup system.

## Secrets

Samba authentication credentials are intentionally excluded from Git.

The deployment uses the following environment variables:

\`\`\`
SAMBA_USER
SAMBA_PASSWORD
\`\`\`

A sanitized \`.env.example\` should be used as a template when
recreating the deployment.

Copy:

\`\`\`
.env.example -> .env
\`\`\`

and provide the required values before starting the service.

Secrets should never be committed to Git.

## Runtime Data

Samba runtime state and the underlying shared storage are intentionally
excluded from Git.

The repository contains deployment configuration rather than the files
made available through the Samba shares.

## Backup

The Docker LXC containing Samba is protected by the normal Proxmox
backup process.

The underlying shared storage is protected separately by the homelab
storage and backup strategy.

The exported Samba configuration is also tracked in the homelab Git
repository.

## Configuration Management

This documentation is generated by:

\`\`\`
scripts/export-configs.sh
\`\`\`

The README is regenerated during each configuration export.

EOF

    record_status "samba" "OK"
}
